language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - pip install requests
    - pip install lxml

script:
    - python setup.py test

after_success:
    - pip install coveralls
    - coverage run --source=burglar setup.py -q nosetests
    - coveralls

notifications:
    email: false
